blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://makerkit.dev/docs
    about: For documentation and tutorials.
  - name: Discord
    url: https://discord.gg/3hBn3nhbgD
    about: For chatting with the community and getting help.
  - name: Administrative Requests (licenses, etc.)
    url: https://makerkit.dev/contact
    about: Please report administrative requests here.